/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp -a MumeSrvAdaptor mumesrv.xml
 *
 * qdbusxml2cpp is Copyright (C) 2015 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef MUMESRVADAPTOR_H
#define MUMESRVADAPTOR_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface ch.bitzgi.MumeSrv
 */
class MumeSrvAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "ch.bitzgi.MumeSrv")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"ch.bitzgi.MumeSrv\">\n"
"    <property access=\"read\" type=\"b\" name=\"switchOn\"/>\n"
"  </interface>\n"
        "")
public:
    MumeSrvAdaptor(QObject *parent);
    virtual ~MumeSrvAdaptor();

public: // PROPERTIES
    Q_PROPERTY(bool switchOn READ switchOn)
    bool switchOn() const;

public Q_SLOTS: // METHODS
Q_SIGNALS: // SIGNALS
};

#endif
